# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/startux/Games/UnrealEngine

TARGETS = \
	Virtue-Android-DebugGame  \
	Virtue-Android-Development  \
	Virtue-Android-Shipping  \
	Virtue-Linux-DebugGame  \
	Virtue-Linux-Development  \
	Virtue-Linux-Shipping  \
	Virtue-LinuxArm64-DebugGame  \
	Virtue-LinuxArm64-Development  \
	Virtue-LinuxArm64-Shipping  \
	Virtue \
	VirtueEditor-Linux-DebugGame  \
	VirtueEditor-Linux-Development  \
	VirtueEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend VirtueEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug VirtueEditor-Linux-Debug


Virtue-Android-DebugGame:
	 $(BUILD) Virtue Android DebugGame  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-Android-Development:
	 $(BUILD) Virtue Android Development  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-Android-Shipping:
	 $(BUILD) Virtue Android Shipping  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-Linux-DebugGame:
	 $(BUILD) Virtue Linux DebugGame  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-Linux-Development:
	 $(BUILD) Virtue Linux Development  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-Linux-Shipping:
	 $(BUILD) Virtue Linux Shipping  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-LinuxArm64-DebugGame:
	 $(BUILD) Virtue LinuxArm64 DebugGame  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-LinuxArm64-Development:
	 $(BUILD) Virtue LinuxArm64 Development  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue-LinuxArm64-Shipping:
	 $(BUILD) Virtue LinuxArm64 Shipping  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

Virtue: Virtue-Linux-Development

VirtueEditor-Linux-DebugGame:
	 $(BUILD) VirtueEditor Linux DebugGame  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

VirtueEditor-Linux-Development:
	 $(BUILD) VirtueEditor Linux Development  -Project="/home/startux/Code/Virtue/Virtue.uproject" $(ARGS)

VirtueEditor: VirtueEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/startux/Code/Virtue/Virtue.uproject" -Game 

.PHONY: $(TARGETS)
